// src/adapters/primaries/react/components/FullPostComponent/FullPostComponent.js
import React from 'react';
import { Link } from 'react-router-dom';
import FetchPosts from '../../../../../business/usecases/FetchPosts';
import { getInstanceApi } from '../../../../secondaries/factoryApiPosts';

import './style.scss';

export default class FullPostComponent extends React.Component{

    constructor(props){
        super(props);
        this.api = new FetchPosts(getInstanceApi());
        this.state = {
            post: null
        };
    }// constructor()

    componentDidMount = async () => {
        const id = this.props.match.params.id;
        const post = await this.api.findById(id);
        this.setState({ post });
    }

    render = () => (<article id="post">
                <h1 id="post-title">{this.state.post && this.state.post.title}</h1>
                <p id="post-content">{this.state.post && this.state.post.body}</p>
                <Link className="btn" to='/'>Retour</Link>
        </article>)

}// FullPostComponent()

// src/adapters/primaries/angular/app/components/FullPostComponent/fullpost.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import Post from '../../../../../../business/domain/post';
import FetchPosts from '../../../../../../business/usecases/FetchPosts';

@Component({
  selector: 'app-fullpost',
  templateUrl: './fullpost.component.html',
  styleUrls: ['./fullpost.component.scss']
})
export class FullPostComponent implements OnInit {

    post: Post;

    constructor(private route: ActivatedRoute, private fetchPosts: FetchPosts){
      this.post = null;
    }// constructor()

    async ngOnInit (): Promise<void> {
      const id = parseInt(this.route.snapshot.paramMap.get('id'));
      this.post = await this.fetchPosts.findById(id);
    }// ngOnInit()

}
<div class="post">
    <h2 *ngIf="post && post.title">{{ post.title }}</h2>
    <p *ngIf="post && post.body">{{ post.body }}</p>
    <a class="btn btn-read-more" [routerLink]="['']">Retour</a>
</div>
