// src/adapters/primaries/react/components/PostsComponent.js
import React from 'react';
import FetchPosts from '../../../../business/usecases/FetchPosts';
import { getInstanceApi } from '../../../secondaries/factoryApiPosts';
import PostComponent from './PostComponent/PostComponent';

import './common.scss';

export default class PostsComponent extends React.Component{

    constructor(props){
        super(props);
        this.api = new FetchPosts(getInstanceApi());
        this.state = {
            posts: [],
        };
    }

    componentDidMount = async () => {
        const posts = await this.api.getAllPosts();
        this.setState({ posts });
    }

    render = () => (<section id="posts">
        <h1>Some posts</h1>
        { this.state.posts.map(post => <PostComponent key={post.id} id={post.id} body={post.body} title={post.title}  />) }
    </section>)

}// PostsComponent()

// src/adapters/primaries/angular/app/components/PostsComponent/posts.component.ts
import { Component, OnInit } from '@angular/core';
import Post from '../../../../../../business/domain/post';
import FetchPosts from '../../../../../../business/usecases/FetchPosts';

@Component({
  selector: 'app-posts',
  templateUrl: './posts.component.html',
  styleUrls: ['./posts.component.scss']
})
export class PostsComponent implements OnInit {

    posts: Post[];

    constructor(private fetchPosts: FetchPosts){
        this.posts = [];
    }// constructor()

    async ngOnInit (): Promise<void> {
        this.posts = await this.fetchPosts.getAllPosts();
    }// ngOnInit()

}
<section id="posts">
    <h1>Some posts</h1>
    <app-post *ngFor="let post of posts" [title]="post.title" [body]="post.body" [id]="post.id"></app-post>
</section>
