// src/adapters/primaries/react/components/PostComponent/PostComponent.js
import React from 'react';
import { Link } from 'react-router-dom';

import './style.scss';

export default class PostComponent extends React.Component{

    render = () => (<div className="post">
            <h2>{this.props.title}</h2>
            <p>{this.props.body}</p>
            <Link className="btn btn-read-more" to={`post/${this.props.id}`}>Read more</Link>
        </div>)

}// PostComponent()

// src/adapters/primaries/angular/app/components/PostComponent/post.component.ts
import { Component, Input, OnInit } from '@angular/core';
import FetchPosts from '../../../../../../business/usecases/FetchPosts';

@Component({
  selector: 'app-post',
  templateUrl: './post.component.html',
  styleUrls: ['./post.component.scss']
})
export class PostComponent implements OnInit {

    @Input() id: number;

    @Input() title: string;

    @Input() body: string;

    constructor(){
    }// constructor()

    ngOnInit (): void {}// ngOnInit()

}
<div class="post">
    <h2>{{ title }}</h2>
    <p>{{ body }}</p>
    <a class="btn btn-read-more" [routerLink]="['/post', id]">Read more</a>
</div>
